Exception ignored in: <gdb._GdbOutputFile object at 0x7fb8fa55feb0>
Traceback (most recent call last):
  File "/usr/share/gdb/python/gdb/__init__.py", line 43, in flush
    def flush(self):
KeyboardInterrupt: 
